api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.generate_with_keyword), # localhost:8000/api/
]

core/urls.py
from django.urls import path
from .views import HomeView, DetailView, CompareView, SavedListView, save_to_list
from django.contrib.auth.decorators import login_required

app_name = "core"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('detail/<str:id>', DetailView.as_view(), name='detail'),
    path('compare', CompareView.as_view(), name='compare'),
    path('compare/<str:id1>/<str:id2>', CompareView.as_view(), name='compare'),
    path('save-to-list/<str:formula>', save_to_list, name='save-to-list'),
    path('saved-list', login_required(SavedListView.as_view()), name='saved-list')
]

moflow_api/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("api/molecular/", include("mole.urls")),
    path("api/account/", include("account.urls")),
]

mole/models.py
from django.db import models
from account.models import User


class Molecular(models.Model):
    owner = models.ForeignKey(
        User, related_name="moleculars", on_delete=models.CASCADE, null=False
    )
    created = models.DateTimeField(auto_now_add=True)
    formula = models.CharField(max_length=100, blank=True, default="")
    effect = models.CharField(max_length=500, blank=True, default="")
    others = models.CharField(max_length=500, blank=True, default="")

    class Meta:
        ordering = ["created"]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}Moflow+{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<!--include header and some scripts files-->
{% include "header.html" %}
<!-- Generate, Compare, Saved list -->
{% include "navbar.html" %}


<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}


    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/compare.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <form action='{% url "core:compare" %}', method="get">
        {% csrf_token %}
        {{form.as_table}}
        <button type="submit">Compare</button>
      </form>
      {% if data %}
      <p>You compare {{data.mole1}} with {{data.mole2}}</p>

      {% endif %}
    </div>
  </main>

{% endblock content %}

templates/detail.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <h2>{{id}}</h2>

      <form action="{% url 'core:save-to-list' formula=id %}" method="post">
        {% csrf_token %}
        <button type="submit" name='mybtn2' value={{id}}>Save</button>
      </form>
      <button>Save as file</button>
      
    </div>
  </main>

{% endblock content %}

templates/header.html
<h1>Moflow+</h1>

{% if request.user.is_authenticated %}
<a href="{% url 'account_logout' %}">Logout</a>
{% else %}
<a href="{% url 'account_login'} %">Login</a>
<a href="{% url 'account_signup' %}">Signup</a>
{% endif %}

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

      <form action='{% url "core:home" %}', method="get">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Generate</button>
      </form>
      {% if data %}
        <p>You search: {{data.keyword}}</p>
        <p>임의로 추출한 분자식</p>
        <ul>
          {% for molecular in molecular_list %}
            <li><a href="{% url 'core:detail' id=molecular %}">{{molecular|upper}}</a></li>
          {% endfor %}
        </ul>
      {% endif %}
      
      

    </div>
  </main>

{% endblock content %}

templates/navbar.html
<ul>
    <li>
        <a href="{% url 'core:home' %}">
            <span>Generate</span>
        </a>
    </li>
    <li>
        <a href="{% url 'core:compare' %}">Compare</a>
    </li>
    <li>
        <a href="{% url 'core:saved-list' %}">Saved List</a>
    </li>
</ul>

templates/savedList.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <h2>Saved list page</h2>
      {% if moleculars %}
      {% for molecular in moleculars%}
          <li><a href="{% url 'core:detail' id=molecular %}">{{molecular|upper}}</a></li>
      {% endfor %}

      {% endif %}
      
    </div>
  </main>

{% endblock content %}